<div class="error-container">
    <?php echo $this->getErrorMessage() ?>
    <div class="container buttons buttons-set">
        <p class="back-link"><a href="#" class="go-back"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button btn btn-continue">
            <span>
                <span><?php echo $this->__('Continue') ?></span>
            </span>
        </button>
    </div>
</div>
