<?php
$first = true;
$_helper = Mage::helper('blueacorn_addressvalidation');
?>
<form id="validated-address-form" method="post" action="#">

    <h2><?php echo $_helper->getConfig("verify_modaltext", "design") ?></h2>

    <div class="container validated-addresses">
        <?php foreach($this->getAddresses() as $index => $address): ?>
            <input id="address_<?php echo $index ?>" value="<?php echo $index ?>" type="radio" name="validated_address" class="no-style radio"
                <?php if ($first): echo ' checked="checked"'; $first = false; endif; ?>/>
            <label for="address_<?php echo $index ?>">
                <?php echo $address['street1'] ?>
                <?php echo $address['street2'] ?>
                <?php echo $address['city'] . ', ' . $address['state'] . ' ' . $address['postcode'] ?>
            </label>
        <?php endforeach ?>

        <?php if ($originalAddress = $this->getOriginalAddress()): ?>
            <h4><?php echo $this->__("Original Address") ?></h4>

            <input id="address_original" value="original" type="radio" name="validated_address" class="no-style radio original-address" />
            <label for="address_original" class="original-address">
                <?php echo $originalAddress['street1'] ?>
                <?php echo $originalAddress['street2'] ?>
                <?php if (array_key_exists('city', $originalAddress) && array_key_exists('state', $originalAddress)): ?>
                    <?php echo $originalAddress['city'] . ', ' . $originalAddress['state'] . ' ' ?>
                <?php endif ?>
                <?php echo $originalAddress['postcode'] ?>
            </label>
        <?php endif ?>

    </div>
    <div class="container buttons buttons-set">
        <p class="back-link"><a href="#" class="go-back"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" title="<?php echo $this->__("Update Address"); ?>" class="button btn btn-submit">
            <span>
                <span><?php echo $this->__("Update Address"); ?></span>
            </span>
        </button>
    </div>
</form>

<?php if ($originalAddress): ?>
<script type="text/javascript">
    $('validated-address-form').on('change', '.radio', function(event) {
        if ($$('input.original-address').first().checked) {
            $$('#validated-address-form button.btn-submit').first().update('Continue');
        } else {
            $$('#validated-address-form button.btn-submit').first().update('Update Address');
        }
    });
</script>
<?php endif ?>