<?php /* @var $this BlueAcorn_AjaxCart_Block_Js */ ?>
<?php /* @var $this BlueAcorn_AjaxCart_Block_Js */ ?>
<?php
/**
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*
* @copyright  Copyright (c) 2013 Blue Acorn (http://www.blueacorn.com)
* @author: Thomas Slade
* @namespace: BlueAcorn
* @module: AjaxCart
*
* @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/** @var $this BlueAcorn_AjaxCart_Block_Js */
?>

<?php if($this->useAjax()) : ?>
    <script type="text/javascript">

        var ajaxCart;

        if(typeof productAddToCartForm != undefined){
            productAddToCartForm.submit = function(button){

                if (this.validator.validate()) {
                    var e = null;
                    try {
                        ajaxCart = new AjaxCart(this.form);
                    } catch (e) {
                        console.log(e);
                    }

                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                        setTimeout(function(){
                            button.disabled = false;
                        }, 5000);
                    }
                }
            }
        }

    </script>
<?php endif ?>